 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/bet-alfa-app:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/bet-alfa-app:$COMMIT_SHA']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: bash
   args:
   - |
        cat deployment.yaml | sed -e "s/{PROJECT_ID}/${PROJECT_ID}/g;" | sed -e "s/{TEMPLATE_VERSION}/${COMMIT_SHA}/g;"  > deployment_version.yaml
   - |
        gcloud beta run services replace deployment_version.yaml --platform managed --region us-central1 
 images:
 - 'gcr.io/$PROJECT_ID/bet-alfa-app:$COMMIT_SHA'